<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $people_names = [
            "Rola",
            "Sara",
            "Salma",
            'Malak',
            'Lojain',
            'Marina',
            'Mairan',
            "James",
            "Robert",
            "Patricia",
            "John",
            "Jennifer",
            "Michael",
            "William",
            "Barbara",
            "Richard",
            "Susan",
            "Joseph	",
            "Jessica",
            "Thomas",
            "Sarah",
            "Charles",
            "Karen",
            "Christopher",
            "Lisa",
            "Daniel",
            "Nancy",
            "Matthew",
            "Betty",
            "Anthony",
            "Margaret",
            "Mark",
            "Sandra",
            "Donald",
            "Ashley",
            "Steven",
            "Kimberly",
            "Paul",
            'Emily',
            'Andrew',
            'Donna',
            'Joshua',
            'Kenneth',
            'Carol',
            'Kevin',
            'Amanda',
            "Brian",
            "Dorothy",
            "George",
            "Melissa",
            "Timothy",
            "Deborah",
            "Ronald",
            "Stephanie",
            "Edward",
            "Jason",
            "Sharon",
            "Jeffrey",
            "Laura",
            "Ryan",
            "Cynthia",
            "Jacob",
            "Kathleen",
            "Gary",
            "Amy",
            "Nicholas",
            "Angela",
            "Eric",
            "Shirley",
            "Jonathan",
            "Anna",
            "Stephen",
            "Brenda",
            "Larry",
            "Pamela",
            "Justin",
            "Emma",
            "Scott",
            "Nicole",
            "Brandon",
            "Helen",
            "Benjamin",
            "Samantha",
            "Samuel",
            "Steven",
            "Kimberly",
            "Paul",
            'Emily',
            'Andrew',
            'Donna',
            'Joshua',
            'Kenneth',
            'Carol',
            'Kevin',
            'Amanda',
            "Brian",
            "Dorothy",
            'Andrew',
            'Donna',
            'Joshua',
            'Kenneth',
            'Carol',
            'Kevin',
            'Amanda',
            "Brian",
            "Dorothy",

        ];


        $people_last_names = [
            "George",
            "Melissa",
            "Timothy",
            "Deborah",
            "Ronald",
            "Stephanie",
            "Edward",
            "Jason",
            "Sharon",
            "Jeffrey",
            "Laura",
            "Ryan",
            "Cynthia",
            "Jacob",
            "Kathleen",
            "Gary",
            "Amy",
            "Nicholas",
            "Angela",
            "Eric",
            "Shirley",
            "Jonathan",
            "Anna",
            "Stephen",
            "Brenda",
            "Larry",
            "Pamela",
            "Justin",
            "Emma",
            "Scott",
            "Nicole",
            "Brandon",
            "Helen",
            "Benjamin",
            "Samantha",
            "Samuel",
            "Steven",
            "Kimberly",
            "Paul",
            'Emily',
            "Michael",
            "William",
            "Barbara",
            "Richard",
            "Susan",
            "Joseph	",
            "Jessica",
            "Thomas",
            "Sarah",
            "Charles",
            "Karen",
            "Christopher",
            "Lisa",
            "Daniel",
            "Nancy",
            "Matthew",
            "Betty",
            "Anthony",
            "Margaret",
            "Mark",
            "Sandra",
            "Donald",
            "Ashley",
            "Steven",
            "Kimberly",
            "Paul",
            'Emily',
            'Andrew',
            'Donna',
            'Joshua',
            'Kenneth',
            'Carol',
            'Kevin',
            'Amanda',
            "Brian",
            "Dorothy",
            "George",
            "Melissa",
            "Timothy",
            "Deborah",
            "Ronald",
            "Stephanie",
            "Edward",
            "Jason",
            "Sharon",
            "Jeffrey",
            "Laura",
            "Ryan",
            "Cynthia",
            "Jacob",
            "Kathleen",
            "Gary",
            "Amy",
            "Nicholas",
            "Angela",
            "Eric",
            "Shirley",
            "Jonathan",
            "Anna",
            "Stephen",
            "Brenda",
            "Larry",
            "Pamela",
            "Justin",
            "Emma",
            "Scott",
            "Nicole",
            "Brandon",
            "Helen",
            "Benjamin",
            "Samantha",
            "Samuel",
            "Steven",
            "Kimberly",
            "Paul",
            'Emily',
            'Andrew',
            'Donna',
            'Joshua',
            'Kenneth',
            'Carol',
            'Kevin',
            'Amanda',
            "Brian",
            "Dorothy",
            'Andrew',
            'Donna',
            'Joshua',
            'Kenneth',
            'Carol',
            'Kevin',
            'Amanda',
            "Brian",
            "Dorothy",

        ];

        for ($i = 0; $i < 100; $i++) {
            // $forigenKey = 0;
            // if ($i < 20) {
            //     $forigenKey = 1;
            // }
            // if ($i > 19 && $i < 40) {
            //     $forigenKey = 2;
            // }
            // if ($i > 39 && $i < 60) {
            //     $forigenKey = 3;
            // }
            // if ($i > 59 && $i < 80) {
            //     $forigenKey = 4;
            // }
            // if ($i > 79 && $i < 100) {
            //     $forigenKey = 5;
            // }
            \DB::table('patients')->insert([
                'first_name' => $people_names[$i],
                'Last_name' => $people_last_names[$i],
                // 'first_name' => \Str::random(5),
                // 'Last_name' => \Str::random(6),
                // 'phone_number' => '20' + \Str::random(11),
                //'phone_number' => \Str::random(13),
                'phone_number' => '01113499373',

                // 'doctor_id' => $forigenKey,
                // 'admin_id' => $forigenKey,
                'doctor_id' => random_int(1, 5),
                'admin_id' => random_int(1, 5),
                'created_at' => now(),
                'updated_at' => now(),

            ]);



        }
        ;

        // for ($i = 25; $i < 50; $i++) {

        //     \DB::table('patients')->insert([
        //         'first_name' => $people_names[$i],
        //         'Last_name' => $people_last_names[$i],
        //         // 'first_name' => \Str::random(5),
        //         // 'Last_name' => \Str::random(6),
        //         // 'phone_number' => '20' + \Str::random(11),
        //         //'phone_number' => \Str::random(13),
        //         'phone_number' => '01113499373',

        //         'doctor_id' => 1,
        //         'admin_id' => 1,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ]);
        // }
        // ;
    }
}